name: "CodeProject.AI server HA addon"
description: "ALPR"
version: "1.0.0"
slug: "codeproject_ai"
init: false
webui: "http://[HOST]:[PORT:32168]/"
tmpfs: true
ingress: true
ingress_port: 32168
ingress_entry: /
ports:
  32168/tcp: 32168
  32168/udp: 32168
  5000/tcp: null
ports_description:
  32168/tcp: Frontend over tcp
  32168/udp: Frontend over udp
  5000/tcp: legacy port (not required for ingress)
environment:
  TZ: Europe/Budapest
  DATA_DIR: /data/ai-data
  MODULES_PATH: /data/modules
  "Modules:ObjectDetectionNet:AutoStart": False
  "Modules:ObjectDetectionYolo:AutoStart": False
  "Modules:ALPR:AutoStart": True
arch:
  - amd64
